[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-fund --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
